import Link from "next/link";
import { MarketingSite, marketingMetadata, Action, SolarIllustration, ContactBand, FAQ } from "@/components/marketing-site";
const includes = [
  ["Inspección inicial", "Revisamos módulos, cableado, conexiones, protecciones y el estado general visible del sistema."],
  ["Mantenimiento preventivo", "Limpiamos los módulos y realizamos las actividades incluidas en el alcance contratado."],
  ["Verificación y reporte", "Documentamos el estado final, fotografías, hallazgos y recomendaciones."],
  ["Correctivos por separado", "Si detectamos una anomalía, te explicamos el problema y cotizamos la reparación antes de intervenir."],
];
export const metadata = marketingMetadata("Mantenimiento de Paneles Solares en Mérida | SOLARIS Energy Solutions", "Mantenimiento preventivo de sistemas fotovoltaicos: inspección, limpieza, revisión y reporte de hallazgos. Desde $1,500 MXN en Yucatán.", "/mantenimiento");
export default function MaintenancePage() {
  return <MarketingSite topic="Mantenimiento">
    <section id="hero" className="landing-hero"><div className="landing-wrap landing-hero-grid"><div><p className="landing-eyebrow">Mantenimiento fotovoltaico · SOLARIS Nivel 1</p><h1>Mantenimiento profesional <span>para tu sistema solar.</span></h1><p className="landing-intro">Inspeccionamos, limpiamos y revisamos tu instalación para conocer su estado real y detectar problemas a tiempo.</p><p className="landing-price">Desde <strong>$1,500 MXN</strong></p><p className="landing-fine">El precio final depende del número de módulos, ubicación, acceso y condiciones del sistema.</p><div className="landing-actions"><Action href="/contacto?servicio=Mantenimiento">Solicitar cotización</Action><a href="#alcance" className="landing-secondary">Conocer el proceso ↓</a></div></div><SolarIllustration /></div></section>
    <section id="alcance" className="landing-wrap landing-section"><div className="section-heading"><div><p className="landing-eyebrow">¿Qué incluye tu mantenimiento?</p><h2>No solo limpiamos paneles.</h2></div><p>Revisamos, documentamos y te informamos si existe una anomalía que requiera atención.</p></div><div className="scope-grid">{includes.map(([title, text], i) => <article key={title}><span className="step-index">0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="process-line"><span>Proceso SOLARIS</span><p>Inspección <b>→</b> Mantenimiento <b>→</b> Verificación <b>→</b> Reporte</p></div><p className="landing-fine">Los correctivos se realizan solo si se requieren, con cotización y autorización previas.</p></section>
    <section className="soft-section"><div className="landing-wrap landing-section editorial-grid"><div><p className="landing-eyebrow">Más claridad sobre tu instalación</p><h2>Un servicio que queda documentado.</h2><p className="landing-lead">Las fotografías, los reportes y las recomendaciones forman parte del seguimiento de tu sistema.</p><Link className="landing-text-link" href="/pasaporte-solar">Conocer Pasaporte Solar ↗</Link></div><div className="service-options"><h3>¿Tu sistema necesita algo más?</h3><p>También podemos ayudarte con diagnóstico, diagramas, documentación técnica y servicios eléctricos relacionados. Definimos su alcance al conocer tu caso.</p><details id="nivel-2"><summary>Sistemas de 40 módulos o más · Nivel 2</summary><p>SOLARIS puede incorporar monitoreo, análisis de desempeño y mantenimiento predictivo. Revisamos las características del sistema para definir una propuesta.</p></details></div></div></section>
    <section className="landing-wrap landing-section editorial-grid"><div><p className="landing-eyebrow">Preguntas frecuentes</p><h2>Antes de agendar.</h2></div><FAQ questions={[["¿Cada cuánto debo dar mantenimiento?", "La frecuencia depende de la instalación y su entorno. Al revisar tu sistema te recomendamos cuándo programar el siguiente servicio."], ["¿El mantenimiento incluye reparaciones?", "Cualquier reparación o sustitución de componentes se informa y cotiza por separado antes de intervenir."], ["¿Qué pasa si encuentran un problema?", "Documentamos el hallazgo, te explicamos la anomalía y preparamos una cotización del correctivo para tu autorización."], ["¿Necesitan apagar el sistema?", "Depende de la instalación y de las actividades a realizar. Te informamos antes del servicio y realizamos las maniobras necesarias para trabajar de forma segura."], ["¿Cuánto cuesta el mantenimiento?", "Inicia desde $1,500 MXN. El precio depende del número de módulos, ubicación, acceso y condiciones del sistema."], ["¿Atienden viviendas y negocios?", "Sí, atendemos sistemas residenciales y comerciales en Yucatán. Cuéntanos dónde está tu instalación para confirmar la atención."]]} /></section>
    <ContactBand title="Cuidemos tu sistema solar." text="Cuéntanos cuántos paneles tienes y dónde está tu instalación. Preparamos tu cotización y acordamos la fecha contigo." topic="Mantenimiento" />
  </MarketingSite>;
}
