import { MarketingSite, marketingMetadata, Action, PassportArtwork, ContactBand, FAQ, passportBenefits } from "@/components/marketing-site";
export const metadata = marketingMetadata("Pasaporte Solar | El expediente de tu sistema | SOLARIS", "Historial de mantenimiento, fotografías, reportes y documentación de tu sistema fotovoltaico. Conoce el Pasaporte Solar de SOLARIS.", "/pasaporte-solar");
export default function PassportPage() {
  return <MarketingSite topic="Pasaporte Solar">
    <section id="hero" className="landing-hero"><div className="landing-wrap landing-hero-grid"><div><p className="landing-eyebrow">Pasaporte Solar</p><h1>Cada mantenimiento<br /><span>deja historial.</span></h1><p className="landing-intro">Tu sistema tiene una historia. El Pasaporte Solar la reúne en un expediente digital para que puedas consultar lo que SOLARIS revisa, documenta y publica.</p><div className="landing-actions"><Action href="/contacto?servicio=Pasaporte%20Solar">Quiero mi Pasaporte Solar</Action><a href="#que-incluye" className="landing-secondary">Descubrir qué incluye ↓</a></div><p className="landing-tagline">La historia de tu sistema, a un escaneo.</p></div><PassportArtwork /></div></section>
    <section id="que-incluye" className="landing-wrap landing-section"><div className="section-heading"><div><p className="landing-eyebrow">Tu expediente, organizado</p><h2>La información que necesitas.<br />En un mismo lugar.</h2></div><p>Desde tu celular o computadora, a través del enlace o QR de tu sistema.</p></div><div className="benefit-grid">{passportBenefits.map(({ icon: Icon, title, text }) => <article key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="soft-section"><div className="landing-wrap landing-section editorial-grid"><div><p className="landing-eyebrow">Así se construye tu historial</p><h2>Del servicio<br />a tu expediente.</h2><p className="landing-lead">Cada registro te ayuda a dar continuidad al cuidado de tu instalación.</p></div><ol className="numbered-steps"><li><span>01</span><div><h3>Revisamos tu sistema</h3><p>Definimos y realizamos las actividades del servicio contratado.</p></div></li><li><span>02</span><div><h3>Documentamos lo realizado</h3><p>Registramos evidencias, hallazgos y recomendaciones.</p></div></li><li><span>03</span><div><h3>Consultas tu expediente</h3><p>Abre tu enlace o escanea el QR para ver la información publicada.</p></div></li></ol></div></section>
    <section className="landing-wrap landing-section editorial-grid"><div><p className="landing-eyebrow">Antes de comenzar</p><h2>Conoce tu Pasaporte.</h2></div><FAQ questions={[["¿Qué información voy a encontrar?", "La información de tu sistema y los mantenimientos, fotografías, reportes, recomendaciones y documentos que SOLARIS publique en tu expediente."], ["¿Cómo puedo obtenerlo?", "Contáctanos y cuéntanos sobre tu instalación. Te explicamos cómo incorporar el Pasaporte Solar y qué incluye la propuesta para tu sistema."], ["¿Necesito instalar una aplicación?", "No. Consulta tu expediente desde el navegador de tu celular o computadora, usando tu enlace personal o el QR de tu sistema."], ["¿Ya soy cliente, dónde lo consulto?", "Utiliza el enlace que te compartió SOLARIS o el QR de tu instalación. Si no lo encuentras, contáctanos para ayudarte a recuperarlo."]]} /></section>
    <ContactBand title="Dale continuidad al cuidado de tu sistema." text="Conoce cómo incorporar el Pasaporte Solar a tu instalación." topic="Pasaporte Solar" />
  </MarketingSite>;
}
