import Link from "next/link";
import { ArrowUpRight, Wrench, FileCheck2 } from "lucide-react";
import { MarketingSite, marketingMetadata, Action, PassportArtwork, ContactBand } from "@/components/marketing-site";

export const metadata = marketingMetadata("Pasaporte Solar y servicios fotovoltaicos | SOLARIS Energy Solutions", "Conoce el Pasaporte Solar: el expediente digital de tu sistema. Mantenimiento fotovoltaico, gestoría CFE y orientación en Yucatán.", "/");
export default function HomePage() {
  return <MarketingSite>
    <section id="hero" className="landing-hero home-hero"><div className="landing-wrap landing-hero-grid"><div className="landing-hero-copy"><p className="landing-eyebrow">SOLARIS Energy Solutions · Yucatán</p><h1>Tu sistema solar.<br /><span>Una historia<br className="desktop-break" /> bien cuidada.</span></h1><p className="hero-product">Conoce el <strong>Pasaporte Solar.</strong></p><p className="landing-intro">El expediente digital para consultar los mantenimientos, reportes y documentos de tu instalación desde tu enlace o código QR.</p><div className="landing-actions"><Action href="/pasaporte-solar">Conocer Pasaporte Solar</Action><Action href="/contacto" secondary>Solicitar orientación</Action></div><p className="landing-tagline">Iluminando el mañana</p></div><PassportArtwork /></div></section>
    <div id="pasaporte" className="home-ribbon"><div className="landing-wrap"><span>Un sistema con historial.</span><p>Mantenimientos <i /> Reportes <i /> Documentos</p><Link href="/pasaporte-solar">Todo en tu Pasaporte <ArrowUpRight size={18} aria-hidden="true" /></Link></div></div>
    <section id="servicios" className="landing-section landing-wrap"><div className="section-heading"><div><p className="landing-eyebrow">Servicios SOLARIS</p><h2>¿En qué etapa está tu sistema?</h2></div><p>Te acompañamos en su cuidado y en los trámites que necesita.</p></div><div className="service-grid"><Link className="service-card maintenance-card" href="/mantenimiento"><div className="service-card-top"><Wrench aria-hidden="true" /><span>01 / CUIDADO DEL SISTEMA</span></div><h3>Mantenimiento<br /> fotovoltaico</h3><p>Inspeccionamos, limpiamos, revisamos y documentamos. Conoce el estado de tu instalación y los hallazgos que requieren atención.</p><span className="card-link">Conocer el mantenimiento <ArrowUpRight aria-hidden="true" /></span></Link><Link className="service-card" href="/gestoria"><div className="service-card-top"><FileCheck2 aria-hidden="true" /><span>02 / TRÁMITES Y DOCUMENTACIÓN</span></div><h3>Gestoría<br /> y trámites CFE</h3><p>Interconexión, nuevos servicios y medidor bidireccional. Te orientamos según tu caso y la etapa de tu trámite.</p><span className="card-link">Explorar gestoría <ArrowUpRight aria-hidden="true" /></span></Link></div></section>
    <ContactBand title="No tienes que saber por dónde empezar." text="Cuéntanos qué necesitas: cuidar tu instalación, organizar su historial o avanzar con un trámite. Te orientamos para dar el siguiente paso." />
  </MarketingSite>;
}
