import type { Metadata } from "next";
import { ArrowDown, ArrowUpRight, Check, ClipboardCheck, FileCheck, Gauge, QrCode, Sun, Wrench, Zap } from "lucide-react";
import { ProspectContact } from "@/components/prospect-contact";

export const metadata: Metadata = {
  title: "Solaris | Mantenimiento solar y gestoría eléctrica",
  description: "Mantenimiento fotovoltaico, diagnóstico y gestoría eléctrica en Yucatán. Solicita una cotización, visita o información.",
};

const services = [
  { icon: Sun, n: "01", title: "Mantenimiento fotovoltaico", text: "Cuidado para tu instalación solar: limpieza de módulos, revisión visual y atención preventiva según las condiciones de tu sistema.", items: ["Limpieza de paneles", "Revisión de la instalación", "Recomendaciones de mantenimiento"] },
  { icon: Gauge, n: "02", title: "Revisión y diagnóstico", text: "¿Notas cambios en tu sistema o necesitas revisar una falla? Evaluamos el caso para definir los siguientes pasos y el alcance del servicio.", items: ["Inspección del sistema", "Identificación de incidencias", "Propuesta de atención"] },
  { icon: FileCheck, n: "03", title: "Gestoría de interconexión", text: "Te acompañamos en la preparación y el seguimiento del trámite para conectar tu sistema fotovoltaico a la red eléctrica.", items: ["Revisión inicial de tu caso", "Orientación sobre documentación", "Seguimiento del trámite"] },
  { icon: Zap, n: "04", title: "Nuevos servicios eléctricos", text: "Apoyo para gestionar una nueva contratación de servicio eléctrico, de acuerdo con las características del inmueble y los requisitos aplicables.", items: ["Evaluación de la solicitud", "Apoyo con requisitos", "Acompañamiento del proceso"] },
  { icon: ClipboardCheck, n: "05", title: "Medidor bidireccional", text: "Gestoría para solicitar el cambio a un medidor bidireccional cuando corresponda al proceso de interconexión de tu instalación.", items: ["Revisión del estado del trámite", "Orientación para la solicitud", "Seguimiento ante el suministrador"] },
];

export default function HomePage() {
  const whatsapp = "527778311043";
  return <main className="bg-[#F5F7FA] text-[#06131B]">
    <header className="border-b border-white/10 bg-[#06131B] text-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-6 py-5"><a href="#" className="flex items-center gap-3"><Sun className="size-9 text-[#F4B400]" /><span className="text-lg font-semibold tracking-[.18em]">SOLARIS<span className="block text-[8px] font-normal tracking-[.2em] text-[#FFD966]">SOLUCIONES ENERGÉTICAS</span></span></a><nav aria-label="Navegación principal" className="flex items-center gap-5 text-xs sm:text-sm"><a href="#servicios" className="hover:text-[#FFD966]">Servicios</a><a href="#proceso" className="hover:text-[#FFD966]">Cómo trabajamos</a><a href="#contacto" className="rounded-full border border-[#F4B400]/60 px-4 py-2 text-[#FFD966]">Hablemos</a></nav></div></header>
    <section className="relative overflow-hidden bg-[#06131B] text-white"><div aria-hidden="true" className="absolute -right-40 top-0 size-[600px] rounded-full bg-[#F4B400]/10 blur-[100px]" /><div className="relative mx-auto grid max-w-7xl items-center gap-16 px-6 py-20 md:py-28 lg:grid-cols-[1.2fr_1fr]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#FFD966]">Cuidamos la energía de tu hogar</p><h1 className="mt-7 max-w-3xl text-5xl font-medium leading-[1.05] tracking-[-.045em] sm:text-6xl lg:text-7xl">Tu energía solar,<br /><span className="text-[#F4B400]">bien acompañada.</span></h1><p className="mt-7 max-w-xl text-base leading-8 text-stone-300">Mantenimiento, diagnóstico y gestoría eléctrica. Un equipo para ayudarte a cuidar tu sistema y avanzar con tus trámites.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#contacto" className="inline-flex items-center gap-3 rounded-full bg-[#F4B400] px-6 py-4 font-semibold" style={{color:'#06131B'}}>Solicitar cotización <ArrowUpRight className="size-5" /></a><a href="#servicios" className="inline-flex items-center gap-3 rounded-full border border-white/20 px-6 py-4">Explorar servicios <ArrowDown className="size-4" /></a></div><p className="mt-8 text-xs text-stone-400">Atención en Yucatán · Viviendas y negocios</p></div><div aria-hidden="true" className="relative rounded-[2rem] border border-white/15 bg-white/[.03] p-8 shadow-2xl"><div className="flex items-center justify-between"><span className="text-[10px] tracking-[.22em] text-stone-300">EL FUTURO SE CUIDA HOY</span><Sun className="size-10 text-[#F4B400]" /></div><div className="my-12 grid -skew-y-6 grid-cols-3 gap-3">{Array.from({length:9}, (_,i) => <div key={i} className="aspect-[1.35] rounded-md border border-sky-200/25 bg-gradient-to-br from-[#284D64] to-[#0B2130] shadow-lg" style={{backgroundImage:'linear-gradient(90deg,transparent 48%,#ffffff18 50%,transparent 52%),linear-gradient(transparent 48%,#ffffff18 50%,transparent 52%),linear-gradient(140deg,#284D64,#0B2130)',backgroundSize:'33% 100%,100% 33%,100% 100%'}} />)}</div><div className="flex justify-between border-t border-white/10 pt-6 text-sm"><span className="text-stone-300">Energía hoy.</span><span className="text-[#FFD966]">Tranquilidad mañana.</span></div></div></div></section>
    <section id="servicios" className="mx-auto max-w-7xl scroll-mt-6 px-6 py-20"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#8A6200]">Lo que hacemos</p><div className="mt-4 grid gap-5 md:grid-cols-2"><h2 className="text-4xl font-medium tracking-tight">Soluciones para cada etapa.</h2><p className="max-w-lg text-stone-500 leading-7">Desde el cuidado de tus paneles hasta el seguimiento de un trámite. Cuéntanos qué necesitas y definimos contigo el alcance del servicio.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(({icon:Icon,n,title,text,items}) => <article key={n} className="flex flex-col rounded-3xl border border-stone-200 bg-white p-7 transition hover:border-[#F4B400] hover:shadow-[0_12px_35px_#06131B0a]"><div className="flex items-center justify-between"><Icon className="size-7 text-[#8A6200]" /><span className="text-xs text-stone-400">/{n}</span></div><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-4 text-sm leading-7 text-stone-500">{text}</p><ul className="my-6 space-y-3">{items.map(item => <li key={item} className="flex gap-2 text-sm"><Check className="mt-0.5 size-4 shrink-0 text-[#8A6200]" />{item}</li>)}</ul><a href="#contacto" className="mt-auto flex items-center justify-between border-t border-stone-100 pt-5 text-sm font-semibold">Consultar este servicio <ArrowUpRight className="size-4" /></a></article>)}<article className="flex flex-col justify-between rounded-3xl bg-[#06131B] p-8 text-white"><Wrench className="size-8 text-[#F4B400]" /><div className="my-10"><h3 className="text-2xl font-medium">¿No sabes por dónde empezar?</h3><p className="mt-4 text-sm leading-7 text-stone-300">Cuéntanos tu situación. Te ayudamos a identificar el servicio o la revisión que necesitas.</p></div><a href="#contacto" className="font-semibold text-[#FFD966]">Solicitar orientación ↗</a></article></div><p className="mt-6 max-w-3xl text-xs leading-6 text-stone-500">Las gestorías están sujetas a la revisión de cada caso y a los requisitos del suministrador. La autorización, los plazos y la ejecución del cambio de medidor corresponden a la entidad responsable.</p></section>
    <section id="proceso" className="border-y border-stone-200 bg-white"><div className="mx-auto max-w-7xl px-6 py-20"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#8A6200]">Así de claro</p><h2 className="mt-4 text-4xl font-medium tracking-tight">Del primer mensaje al siguiente paso.</h2><div className="mt-12 grid gap-8 md:grid-cols-3">{[['01','Cuéntanos tu caso','Selecciona un servicio y envíanos tu solicitud de cotización, visita o información.'],['02','Definimos lo necesario','Revisamos tu solicitud y te indicamos si hace falta una visita o información adicional.'],['03','Confirmamos contigo','Acordamos el alcance, la cotización y la fecha antes de iniciar el servicio.']].map(([n,title,text]) => <div key={n}><span className="text-4xl font-light text-[#D5A526]">{n}</span><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-stone-500">{text}</p></div>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl items-center gap-10 px-6 py-20 md:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#8A6200]">Pasaporte solar</p><h2 className="mt-4 text-4xl font-medium tracking-tight">La historia de tu sistema,<br />a un escaneo.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-stone-500">Las viviendas registradas cuentan con un expediente digital para consultar mantenimientos, fotografías, reportes y recomendaciones publicados por Solaris.</p><p className="mt-5 text-sm font-semibold">¿Ya eres cliente? Abre el enlace de tu expediente o escanea el QR de tu vivienda.</p></div><div className="rounded-3xl border border-stone-200 bg-white p-8"><QrCode className="size-10 text-[#8A6200]" /><p className="mt-6 text-xs uppercase tracking-wider text-[#8A6200]">Tu expediente digital</p><div className="mt-6 space-y-4">{['Historial de servicios','Documentos y fotografías','Próximo mantenimiento'].map(text => <div key={text} className="flex items-center justify-between rounded-xl bg-stone-50 p-4 text-sm"><span>{text}</span><Check className="size-4 text-[#8A6200]" /></div>)}</div></div></section>
    <section id="contacto" className="bg-[#06131B] text-white"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-20 lg:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#FFD966]">Hablemos de tu proyecto</p><h2 className="mt-5 text-4xl font-medium tracking-tight md:text-5xl">El siguiente paso<br />empieza contigo.</h2><p className="mt-6 max-w-md leading-8 text-stone-300">Solicita una cotización, una visita o más información. Describe lo que necesitas y nuestro equipo dará seguimiento a tu consulta.</p><div className="mt-8 space-y-3 text-sm"><p>Atención en Yucatán</p><a href="https://wa.me/527778311043" target="_blank" rel="noreferrer" className="block text-[#FFD966]">WhatsApp: 777 831 1043 ↗</a><a href="mailto:solarisenergysolutions.mx@gmail.com" className="block break-all text-[#FFD966]">solarisenergysolutions.mx@gmail.com ↗</a></div><div className="mt-10 space-y-4 text-sm text-stone-300"><p>✓ Atención según las necesidades de tu instalación</p><p>✓ Alcance y condiciones antes de comenzar</p><p>✓ Seguimiento de tu solicitud</p></div></div><ProspectContact whatsapp={whatsapp} /></div></section>
    <section className="mx-auto max-w-3xl px-6 py-20"><h2 className="mb-8 text-3xl font-medium tracking-tight">Antes de escribirnos</h2>{[['¿Puedo solicitar una visita?','Sí. Selecciona «una visita» en el formulario e indica tu zona. El equipo confirmará disponibilidad, alcance y posibles costos antes de agendar.'],['¿Pueden revisar un sistema que instaló otra empresa?','Cuéntanos las características de tu instalación y el servicio que necesitas para revisar si podemos atenderlo.'],['¿La solicitud confirma una cita?','El mensaje inicia la atención. La fecha, el costo y el alcance se confirman directamente con el equipo.'],['¿Qué necesito para una gestoría?','Depende del trámite y de tu caso. Primero cuéntanos qué necesitas; después te indicaremos la documentación que corresponde.']].map(([q,a]) => <details key={q} className="border-b border-stone-200 py-5"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-4 text-sm leading-7 text-stone-500">{a}</p></details>)}</section>
    <footer className="border-t border-stone-200 px-6 py-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5 text-xs text-stone-500"><span>SOLARIS · Soluciones energéticas</span><span>© {new Date().getFullYear()} Solaris</span><a href="/admin">Administración</a></div></footer>
  </main>;
}
