'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import { FileText, Plus, Save, Sparkles, X, ArrowLeft, ArrowRight, Download, CheckCircle2 } from 'lucide-react';
import type { AdminSystem } from '@/lib/admin-system';
import { getSupabaseBrowserClient } from '@/lib/supabase/client';
import { emptyService, EVIDENCE_BUCKET, factualConclusion, findingStates, generalStates, organizeNotes, photoCategories, priorities, reportFilename, serviceTypes, validateService, type ReportRecord, type ServiceDraft, type ServicePhoto, type ServiceRecord } from '@/lib/service-report';
import './service-reports.css';
const steps=['Información general','Sistema','Trabajo realizado','Hallazgos','Mediciones','Fotografías','Recomendaciones','Vista previa'];
type Claim={text:string;source:string};
type Proposal={activities:Claim[];findings:{title:string;description:string;state:string;source:string}[];corrections:Claim[];recommendations:{title:string;description:string;priority:string;source:string}[];result:Claim;generalState:Claim;conclusion:Claim[]};
function Field({label,value,onChange,type='text',max=500,required=false,readOnly=false}:{label:string;value:string;onChange:(s:string)=>void;type?:string;max?:number;required?:boolean;readOnly?:boolean}) {return <label>{label}{required?' *':''}<input type={type} value={value} maxLength={max} required={required} readOnly={readOnly} onChange={e=>onChange(e.target.value)}/></label>;}
function Area({label,value,onChange,max=6000}:{label:string;value:string;onChange:(s:string)=>void;max?:number}) {return <label>{label}<textarea rows={4} value={value} maxLength={max} onChange={e=>onChange(e.target.value)}/></label>;}
function Select({label,value,options,onChange}:{label:string;value:string;options:readonly string[];onChange:(s:string)=>void}) {return <label>{label}<select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x} value={x}>{x||'Sin registrar'}</option>)}</select></label>;}
const uid=()=>crypto.randomUUID();
async function photoData(blob:Blob) {
 const bitmap=await createImageBitmap(blob); const canvas=document.createElement('canvas'); const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));
 canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d'); if(!ctx) throw new Error('No se pudo preparar una fotografía.');
 ctx.fillStyle='#ffffff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.85);
}
export function AdminServiceReports({system,onFinalized}:{system:AdminSystem;onFinalized:()=>void}) {
 const [services,setServices]=useState<ServiceRecord[]>([]),[reports,setReports]=useState<ReportRecord[]>([]),[draft,setDraft]=useState<ServiceDraft|null>(null),[record,setRecord]=useState<ServiceRecord|null>(null),[serviceId,setServiceId]=useState(''),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[proposal,setProposal]=useState<Proposal|null>(null),[aiMode,setAiMode]=useState('report'),[preview,setPreview]=useState(''),[pdfBlob,setPdfBlob]=useState<Blob|null>(null),[savedReport,setSavedReport]=useState<ReportRecord|null>(null),[photoUrls,setPhotoUrls]=useState<Record<string,string>>({});
 const editorRef=useRef<HTMLDivElement>(null);
 const load=useCallback(async()=>{const {data,error}=await getSupabaseBrowserClient().rpc('admin_service_list',{p_system_code:system.systemCode});if(error){setMessage('No fue posible cargar los servicios. Comprueba la conexión o la instalación del módulo.');}else{setServices(data.services||[]);setReports(data.reports||[]);}setLoading(false);},[system.systemCode]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer);},[load]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>()=>{if(preview.startsWith('blob:')) URL.revokeObjectURL(preview);},[preview]);
 function change<K extends keyof ServiceDraft>(key:K,value:ServiceDraft[K]) {setDraft(d=>d?{...d,[key]:value,...(key==='verified'?{}:{verified:false})}:d);setDirty(true);setPreview('');setPdfBlob(null);setSavedReport(null);}
 function start(existing?:ServiceRecord) {if(dirty&&!window.confirm('Hay cambios sin guardar. ¿Quieres descartarlos?')) return;const d=existing?structuredClone(existing.data):emptyService();if(!existing){d.location=system.address;d.system.modules=system.numPanels?String(system.numPanels):'';d.system.power=system.numPanels&&system.panelPowerW?`${system.numPanels*system.panelPowerW/1000} kWp`:'';d.system.moduleModel=system.panelBrand;d.system.inverter=system.inverterModel;}
 setServiceId(existing?.id||uid());setRecord(existing||null);setDraft(d);setStep(0);setDirty(false);setPreview('');setPdfBlob(null);setSavedReport(null);setProposal(null);setMessage('');setPhotoUrls({});setTimeout(()=>editorRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),0);}
 async function save(data=draft) {if(!data) throw new Error('Abre un servicio.');const error=validateService(data);if(error) throw new Error(error);const result=await getSupabaseBrowserClient().rpc('admin_save_service',{p_id:serviceId,p_system_code:system.systemCode,p_version:record?.version||0,p_data:data});if(result.error) throw new Error(result.error.message);setRecord(result.data);setDraft(result.data.data);setDirty(false);setSavedReport(null);return result.data as ServiceRecord;}
 async function action(task:()=>Promise<void>){setBusy(true);setMessage('');try{await task();}catch(e){setMessage(e instanceof Error?e.message:'No se pudo completar la acción. Tus datos siguen en el formulario.');}finally{setBusy(false);}}
 async function saveDraft(){await action(async()=>{await save();setPreview('');setPdfBlob(null);await load();setMessage('Borrador guardado. Puedes retomarlo desde cualquier dispositivo.');});}
 async function askAI(mode:'rewrite'|'report'){if(!draft) return;await action(async()=>{const res=await fetch('/api/service-reports/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({notes:draft.originalNotes,mode})});const body=await res.json();if(!res.ok) throw new Error(body.error);setProposal(body.proposal);setAiMode(mode);});}
 function applyProposal(){if(!proposal||!draft)return;const next={...draft,activities:proposal.activities.map(x=>x.text).join('\n'),verified:false};if(aiMode==='report'){next.findings=[...draft.findings,...proposal.findings.map(f=>({id:uid(),title:f.title,description:f.description,state:f.state}))];next.recommendations=[...draft.recommendations,...proposal.recommendations.map(r=>({id:uid(),title:r.title,description:r.description,priority:r.priority}))];next.corrections=proposal.corrections.map(x=>x.text).join('\n');next.result=proposal.result.text;next.generalState=proposal.generalState.text;next.conclusion=proposal.conclusion.map(x=>x.text).join('\n\n');}setDraft(next);setDirty(true);setProposal(null);setPreview('');setPdfBlob(null);setSavedReport(null);setMessage('Propuesta incorporada. Revisa y edita los campos; las notas originales se conservaron.');}
 async function upload(files:FileList|null){if(!files||!draft)return;await action(async()=>{if(draft.photos.length+files.length>40)throw new Error('Máximo 40 fotografías por servicio.');const added:ServicePhoto[]=[];let failure='';for(const file of Array.from(files)){try{if(!['image/jpeg','image/png'].includes(file.type)||file.size>15*1024*1024)throw new Error('Usa fotografías JPG o PNG de hasta 15 MB.');const id=uid(),path=`${serviceId}/photos/${id}.${file.type==='image/png'?'png':'jpg'}`;const data=await photoData(file);const result=await getSupabaseBrowserClient().storage.from(EVIDENCE_BUCKET).upload(path,file,{upsert:false,contentType:file.type});if(result.error)throw new Error('No se pudo guardar una fotografía. Intenta nuevamente.');added.push({id,path,description:file.name.replace(/\.[^.]+$/,''),category:'Evidencia general',findingIds:[]});setPhotoUrls(old=>({...old,[id]:data}));}catch(e){failure=e instanceof Error?e.message:'Carga incompleta';break;}}if(added.length)change('photos',[...draft.photos,...added]);if(failure)throw new Error(failure+' Las fotografías cargadas aparecen abajo.');});}
 async function generate(){if(!draft)return;await action(async()=>{const error=validateService(draft,true);if(error)throw new Error(error);const stored=await save();const db=getSupabaseBrowserClient(),images:Record<string,string>={};for(const photo of stored.data.photos){const result=await db.storage.from(EVIDENCE_BUCKET).download(photo.path);if(result.error||!result.data)throw new Error('No se pudo leer una fotografía. No se generó un PDF incompleto.');images[photo.id]=await photoData(result.data);}setPhotoUrls(images);const {buildServicePdf}=await import('@/components/service-report-pdf');const blob=await buildServicePdf(stored,images,window.location.origin);if(blob.size>15*1024*1024)throw new Error('El reporte supera 15 MB. Reduce la cantidad de fotografías.');setPdfBlob(blob);setPreview(URL.createObjectURL(blob));setMessage('Vista previa generada. Revisa el PDF completo antes de guardarlo o finalizar.');await load();});}
 async function persistReport(){if(savedReport)return savedReport;if(!record||!pdfBlob||dirty)throw new Error('Genera la vista previa de la versión actual.');const id=uid(),path=`${serviceId}/reports/${id}.pdf`;const db=getSupabaseBrowserClient();const uploaded=await db.storage.from(EVIDENCE_BUCKET).upload(path,pdfBlob,{upsert:false,contentType:'application/pdf'});if(uploaded.error)throw new Error('No fue posible guardar el PDF. Puedes descargarlo e intentar de nuevo.');const result=await db.rpc('admin_store_service_report',{p_id:id,p_service_id:serviceId,p_version:record.version,p_path:path});if(result.error)throw new Error(result.error.message);setSavedReport(result.data);await load();return result.data as ReportRecord;}
 async function finalize(){await action(async()=>{const report=await persistReport();const db=getSupabaseBrowserClient();const stored=await db.storage.from(EVIDENCE_BUCKET).download(report.file_path);if(stored.error||!stored.data)throw new Error('No se pudo recuperar el PDF guardado.');const publicPath=`${system.systemCode}/reports/${report.id}.pdf`;const uploaded=await db.storage.from('system-documents').upload(publicPath,stored.data,{upsert:false,contentType:'application/pdf'});if(uploaded.error){const existing=await db.storage.from('system-documents').download(publicPath);if(existing.error)throw new Error('No se pudo publicar el reporte. El PDF privado está guardado; puedes reintentar.');const hash=async(b:Blob)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await b.arrayBuffer()))).join(',');if(await hash(existing.data)!==await hash(stored.data))throw new Error('El archivo publicado no coincide con el PDF revisado.');}const {data}=db.storage.from('system-documents').getPublicUrl(publicPath);const result=await db.rpc('admin_finalize_service',{p_service_id:serviceId,p_report_id:report.id,p_file_url:data.publicUrl});if(result.error)throw new Error(result.error.message);setDraft(null);setDirty(false);setPreview('');setPdfBlob(null);await load();setMessage('Servicio finalizado. El reporte ya está en el historial y los documentos del cliente.');onFinalized();});}
 async function openReport(report:ReportRecord){await action(async()=>{const result=await getSupabaseBrowserClient().storage.from(EVIDENCE_BUCKET).download(report.file_path);if(result.error)throw new Error('No se pudo abrir el PDF.');setPreview(URL.createObjectURL(result.data));setPdfBlob(result.data);setRecord(report.snapshot);setDraft(null);setSavedReport(report);});}
 const linkName=record?reportFilename(record):'SOLARIS_Reporte.pdf';
 return <section className="service-module" aria-labelledby="service-title"><div className="sr-heading"><div><p className="sr-eyebrow">Expediente · {system.systemCode}</p><h3 id="service-title">Mantenimientos / Servicios</h3><p>Captura el trabajo, revisa el reporte y conserva cada versión.</p></div><button className="sr-primary" disabled={busy} onClick={()=>start()}><Plus size={17}/>Nuevo servicio</button></div>
 {message&&<p role="status" className="sr-message">{message}</p>}
 {loading?<p>Cargando servicios…</p>:<div className="sr-service-list">{!services.length&&<p className="sr-muted">Todavía no hay servicios en este módulo. Los mantenimientos anteriores se conservan en el historial.</p>}{services.map(s=><article key={s.id}><div><strong>{s.folio}</strong><p>{s.data.type} · {s.data.date} · {s.status==='completed'?'Finalizado':'Borrador'}</p></div>{s.status==='draft'&&<button disabled={busy} onClick={()=>start(s)}>Continuar borrador</button>}<div>{reports.filter(r=>r.service_id===s.id).map(r=><button key={r.id} disabled={busy} onClick={()=>{if(dirty&&!window.confirm('Hay cambios sin guardar. ¿Quieres descartarlos?'))return;setDirty(false);void openReport(r);}}><FileText size={15}/>PDF v{r.version}{r.published?' · Final':''}</button>)}</div></article>)}</div>}
 {draft&&<div ref={editorRef} className="sr-editor"><div className="sr-editor-heading"><div><span className="sr-eyebrow">{record?.folio||'Nuevo servicio'} · {system.client.fullName}</span><h4>{steps[step]}</h4></div><button disabled={busy} aria-label="Cerrar editor" onClick={()=>{if(dirty&&!window.confirm('Hay cambios sin guardar. ¿Quieres descartarlos?'))return;setDraft(null);setDirty(false);setPreview('');}}><X size={20}/></button></div><nav aria-label="Pasos del reporte" className="sr-steps">{steps.map((name,i)=><button key={name} aria-current={i===step?'step':undefined} disabled={busy} onClick={()=>setStep(i)}><span>{i+1}</span>{name}</button>)}</nav>
 <fieldset disabled={busy} className="sr-fields">
 {step===0&&<><div className="sr-grid"><Field label="Cliente" value={system.client.fullName} readOnly onChange={()=>{}}/><Field label="Fecha del servicio" value={draft.date} type="date" onChange={v=>change('date',v)} required/><Select label="Tipo de servicio" value={draft.type} options={serviceTypes} onChange={v=>change('type',v)}/><Field label="Técnico responsable" value={draft.technician} onChange={v=>change('technician',v)} max={120} required/></div><Field label="Ubicación" value={draft.location} onChange={v=>change('location',v)} required/><p className="sr-muted">El cliente está vinculado a este expediente. El folio se asigna al guardar.</p></>}
 {step===1&&<><p className="sr-muted">Todos los datos de esta sección son opcionales. Conserva únicamente la información comprobada.</p><div className="sr-grid"><Select label="Tipo de sistema" value={draft.system.type} options={['','Interconectado','Híbrido','Aislado']} onChange={v=>change('system',{...draft.system,type:v})}/>{([['modules','Número de módulos'],['power','Potencia instalada (incluye unidad)'],['moduleModel','Marca y modelo de módulos'],['inverter','Inversor o microinversores'],['batteries','Baterías, si aplica'],['protections','Protecciones principales']] as const).map(([key,label])=><Field key={key} label={label} value={draft.system[key]} onChange={v=>change('system',{...draft.system,[key]:v})}/>)}</div></>}
 {step===2&&<><Area label="Notas originales del técnico" value={draft.originalNotes} max={12000} onChange={v=>{change('originalNotes',v);setProposal(null);}}/><p className="sr-muted">Se conservan tal como las escribes. La IA solo recibe estas notas, no las fotografías ni los datos de contacto.</p><div className="sr-actions"><button onClick={()=>change('activities',organizeNotes(draft.originalNotes))}>Organizar notas en lista</button><button onClick={()=>void askAI('rewrite')}><Sparkles size={16}/>Mejorar redacción</button><button onClick={()=>void askAI('report')}><Sparkles size={16}/>Generar reporte con IA</button></div>{proposal&&<div className="sr-proposal"><h4>Propuesta de IA · pendiente de revisión</h4><p>Confirma cada afirmación con las notas originales. Incorporar reemplaza la redacción de esta sección; los hallazgos y recomendaciones se agregan a los existentes.</p>{[...proposal.activities,...proposal.findings.map(f=>({text:`${f.title}: ${f.description} (${f.state})`,source:f.source})),...proposal.corrections,...proposal.recommendations.map(r=>({text:`${r.title}: ${r.description} (${r.priority})`,source:r.source})),proposal.result,proposal.generalState,...proposal.conclusion].filter(x=>x.text).map((x,i)=><blockquote key={i}><p>{x.text}</p><small>Respaldo: {x.source||'No hay información suficiente para verificar la operación.'}</small></blockquote>)}<div className="sr-actions"><button onClick={applyProposal}>Incorporar y editar</button><button onClick={()=>setProposal(null)}>Descartar propuesta</button></div></div>}<Area label="Servicio realizado (una actividad por línea)" value={draft.activities} onChange={v=>change('activities',v)}/><Area label="Acciones correctivas realizadas" value={draft.corrections} onChange={v=>change('corrections',v)}/><Area label="Resultado de las acciones y pruebas realizadas" value={draft.result} onChange={v=>change('result',v)}/></>}
 {step===3&&<>{draft.findings.map((f,i)=><article className="sr-entry" key={f.id}><div className="sr-entry-heading"><strong>Hallazgo {i+1}</strong><button aria-label={`Quitar hallazgo ${i+1}`} onClick={()=>{change('findings',draft.findings.filter(x=>x.id!==f.id));change('photos',draft.photos.map(p=>({...p,findingIds:p.findingIds.filter(id=>id!==f.id)})));}}><X size={17}/></button></div><Field label="Título" value={f.title} onChange={v=>change('findings',draft.findings.map(x=>x.id===f.id?{...x,title:v}:x))}/><Area label="Descripción" value={f.description} max={1800} onChange={v=>change('findings',draft.findings.map(x=>x.id===f.id?{...x,description:v}:x))}/><Select label="Estado" value={f.state} options={findingStates} onChange={v=>change('findings',draft.findings.map(x=>x.id===f.id?{...x,state:v}:x))}/></article>)}<button disabled={draft.findings.length>=40} onClick={()=>change('findings',[...draft.findings,{id:uid(),title:'',description:'',state:'Requiere atención'}])}><Plus size={16}/>Agregar hallazgo</button><p className="sr-muted">Asocia las imágenes en el paso Fotografías.</p></>}
 {step===4&&<><p className="sr-muted">Opcional. Si no agregas mediciones, esta sección no aparecerá en el PDF. No se interpretan automáticamente los valores.</p>{draft.measurements.map((m,i)=><article className="sr-entry" key={m.id}><div className="sr-entry-heading"><strong>Medición {i+1}</strong><button aria-label={`Quitar medición ${i+1}`} onClick={()=>change('measurements',draft.measurements.filter(x=>x.id!==m.id))}><X size={17}/></button></div><div className="sr-grid">{([['parameter','Parámetro'],['value','Valor'],['unit','Unidad'],['observation','Observación']] as const).map(([key,label])=><Field key={key} label={label} value={m[key]} max={key==='observation'?300:100} onChange={v=>change('measurements',draft.measurements.map(x=>x.id===m.id?{...x,[key]:v}:x))}/>)}</div></article>)}<button disabled={draft.measurements.length>=40} onClick={()=>change('measurements',[...draft.measurements,{id:uid(),parameter:'',value:'',unit:'',observation:''}])}><Plus size={16}/>Agregar medición</button></>}
 {step===5&&<><label className="sr-upload">Subir fotografías<input type="file" accept="image/jpeg,image/png" multiple onChange={e=>{void upload(e.target.files);e.target.value='';}}/></label><p className="sr-muted">JPG o PNG, hasta 15 MB por foto. La evidencia del borrador es privada. El PDF final incluirá las fotografías seleccionadas.</p><div className="sr-photo-grid">{draft.photos.map((p,i)=><article className="sr-entry" key={p.id}><div className="sr-entry-heading"><strong>Foto {i+1}</strong><button aria-label={`Quitar foto ${i+1} del reporte`} onClick={()=>change('photos',draft.photos.filter(x=>x.id!==p.id))}><X size={17}/></button></div>{photoUrls[p.id]?<Image src={photoUrls[p.id]} alt={p.description} width={400} height={300} unoptimized/>:<button onClick={()=>void action(async()=>{const res=await getSupabaseBrowserClient().storage.from(EVIDENCE_BUCKET).download(p.path);if(res.error)throw new Error('No se pudo abrir la fotografía.');const imageData=await photoData(res.data);setPhotoUrls(x=>({...x,[p.id]:imageData}));})}>Ver fotografía guardada</button>}<Field label="Descripción" value={p.description} max={240} onChange={v=>change('photos',draft.photos.map(x=>x.id===p.id?{...x,description:v}:x))}/><Select label="Categoría" value={p.category} options={photoCategories} onChange={v=>change('photos',draft.photos.map(x=>x.id===p.id?{...x,category:v}:x))}/>{draft.findings.length>0&&<div><p>Hallazgos asociados</p>{draft.findings.map(f=><label className="sr-check" key={f.id}><input type="checkbox" checked={p.findingIds.includes(f.id)} onChange={e=>change('photos',draft.photos.map(x=>x.id===p.id?{...x,findingIds:e.target.checked?[...x.findingIds,f.id]:x.findingIds.filter(id=>id!==f.id)}:x))}/>{f.title||'Hallazgo sin título'}</label>)}</div>}</article>)}</div></>}
 {step===6&&<>{draft.recommendations.map((r,i)=><article className="sr-entry" key={r.id}><div className="sr-entry-heading"><strong>Recomendación {i+1}</strong><button aria-label={`Quitar recomendación ${i+1}`} onClick={()=>change('recommendations',draft.recommendations.filter(x=>x.id!==r.id))}><X size={17}/></button></div><Field label="Título" value={r.title} onChange={v=>change('recommendations',draft.recommendations.map(x=>x.id===r.id?{...x,title:v}:x))}/><Area label="Descripción" value={r.description} max={1800} onChange={v=>change('recommendations',draft.recommendations.map(x=>x.id===r.id?{...x,description:v}:x))}/><Select label="Prioridad" value={r.priority} options={priorities} onChange={v=>change('recommendations',draft.recommendations.map(x=>x.id===r.id?{...x,priority:v}:x))}/></article>)}<button disabled={draft.recommendations.length>=40} onClick={()=>change('recommendations',[...draft.recommendations,{id:uid(),title:'',description:'',priority:'Recomendada'}])}><Plus size={16}/>Agregar recomendación</button><Select label="Estado general" value={draft.generalState} options={generalStates} onChange={v=>change('generalState',v)}/><Area label="Comentarios finales" value={draft.finalComments} onChange={v=>change('finalComments',v)}/><Field label="Próximo mantenimiento (opcional)" type="date" value={draft.nextDate} onChange={v=>change('nextDate',v)}/><button onClick={()=>change('conclusion',factualConclusion(draft))}>Preparar conclusión con los datos registrados</button><Area label="Conclusión (máximo tres párrafos)" value={draft.conclusion} max={3000} onChange={v=>change('conclusion',v)}/></>}
 {step===7&&<><p>Genera el PDF para ver exactamente el documento que se guardará. Editar cualquier dato invalida esta vista previa.</p><label className="sr-check"><input type="checkbox" checked={draft.verified} onChange={e=>change('verified',e.target.checked)}/>Revisé las actividades, hallazgos, mediciones, estado y conclusión. Todo corresponde a lo observado y realizado.</label><div className="sr-actions"><button className="sr-primary" onClick={()=>void generate()}><FileText size={17}/>Generar vista previa</button><button onClick={()=>setStep(2)}>Editar</button></div>{preview&&<><div className="sr-pdf"><iframe title="Vista previa exacta del reporte PDF" src={preview}/></div><a href={preview} target="_blank" rel="noreferrer">Abrir PDF en otra pestaña</a><div className="sr-actions"><button onClick={()=>void action(async()=>{await persistReport();setMessage('Reporte guardado como una nueva versión.');})}><Save size={17}/>Generar reporte y guardar</button><a className="sr-button" href={preview} download={linkName}><Download size={17}/>Descargar PDF</a><button className="sr-primary" onClick={()=>void finalize()}><CheckCircle2 size={17}/>Finalizar servicio</button></div><p className="sr-muted">Finalizar publica este reporte en el Pasaporte Solar y bloquea el servicio. Para cambios posteriores se registra un nuevo servicio; los anteriores se conservan.</p></>}</>}
 </fieldset><div className="sr-bottom"><button disabled={busy||step===0} onClick={()=>setStep(x=>x-1)}><ArrowLeft size={16}/>Anterior</button><button disabled={busy} onClick={()=>void saveDraft()}><Save size={16}/>{busy?'Procesando…':'Guardar borrador'}</button><button disabled={busy||step===7} onClick={()=>setStep(x=>x+1)}>Siguiente<ArrowRight size={16}/></button></div>{dirty&&<p className="sr-muted">Hay cambios sin guardar.</p>}</div>}
 {!draft&&preview&&<div className="sr-editor"><div className="sr-heading"><h4>{record?.folio} · Reporte guardado</h4><button onClick={()=>setPreview('')}>Cerrar</button></div><div className="sr-pdf"><iframe title="Reporte guardado" src={preview}/></div><a className="sr-button" href={preview} download={linkName}><Download size={17}/>Descargar PDF</a></div>}
 </section>;
}
