import { Document, Page, Text, View, Image as PdfImage, Link, StyleSheet, pdf } from '@react-pdf/renderer';
import { toDataURL } from 'qrcode';
import type { ServiceRecord } from '@/lib/service-report';
const navy='#06131B',gold='#B48200';
const styles=StyleSheet.create({page:{fontFamily:'Helvetica',fontSize:10,color:navy,paddingTop:42,paddingBottom:56,paddingHorizontal:40,lineHeight:1.5},brand:{fontSize:24,fontFamily:'Helvetica-Bold',letterSpacing:3,height:34,marginBottom:5},subtitle:{fontSize:8,letterSpacing:1.3,color:gold,marginBottom:7},header:{flexDirection:'row',justifyContent:'space-between',borderBottomWidth:2,borderBottomColor:'#F4B400',paddingBottom:16,marginBottom:22},title:{fontSize:19,fontFamily:'Helvetica-Bold',marginBottom:12},section:{fontSize:12,fontFamily:'Helvetica-Bold',marginTop:20,marginBottom:9,color:navy},muted:{fontSize:8,color:'#5D6C7B'},row:{flexDirection:'row',gap:16,marginBottom:8},field:{width:'48%'},label:{fontSize:8,color:'#5D6C7B'},box:{backgroundColor:'#F5F7FA',borderRadius:6,padding:12,marginBottom:8},bold:{fontFamily:'Helvetica-Bold'},body:{marginBottom:6},tableHead:{flexDirection:'row',backgroundColor:navy,color:'#FFFFFF',padding:8,fontFamily:'Helvetica-Bold',fontSize:8},tableRow:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:'#DDE3EA',padding:8,fontSize:9},photo:{width:'48%',marginBottom:16},photoImage:{height:164,width:'100%',objectFit:'contain',backgroundColor:'#F5F7FA'},caption:{fontSize:8,marginTop:5},footer:{position:'absolute',bottom:24,left:40,right:40,flexDirection:'row',justifyContent:'space-between',fontSize:8,color:'#5D6C7B'},contact:{marginTop:24,paddingTop:16,borderTopWidth:1,borderTopColor:'#DDE3EA',flexDirection:'row',justifyContent:'space-between'},qr:{width:80,height:80}});
function Heading({children,ahead=60}:{children:React.ReactNode;ahead?:number}) {return <Text style={styles.section} minPresenceAhead={ahead}>{children}</Text>;}
function Lines({text}:{text:string}) {return <>{text.split('\n').filter(s=>s.trim()).map((line,i)=><Text key={i} style={styles.body} orphans={2} widows={2}>{line}</Text>)}</>;}
export function ServiceReportDocument({record,images,qr,passportUrl,logo}:{record:ServiceRecord;images:Record<string,string>;qr:string;passportUrl:string;logo?:string}) {
 const d=record.data;
 const details=[['Tipo de sistema',d.system.type],['Número de módulos',d.system.modules],['Potencia instalada',d.system.power],['Módulos: marca y modelo',d.system.moduleModel],['Inversor / microinversores',d.system.inverter],['Baterías',d.system.batteries],['Protecciones principales',d.system.protections]].filter(([,value])=>value.trim());
 const photoRows=Array.from({length:Math.ceil(d.photos.length/2)},(_,i)=>d.photos.slice(i*2,i*2+2));
 return <Document title={`Reporte ${record.folio}`} author="SOLARIS Energy Solutions" subject="Reporte final de servicio fotovoltaico" language="es-MX"><Page size="LETTER" style={styles.page}><Text fixed style={{position:"absolute",top:750,left:40,fontSize:8,color:"#5D6C7B",height:15}}>{record.folio} · {d.date}</Text><Text fixed style={{position:"absolute",top:750,right:40,width:120,fontSize:8,color:"#5D6C7B",textAlign:"right"}} render={({pageNumber,totalPages})=>`Página ${pageNumber} de ${totalPages}`}/>
 <View style={styles.header}><View>{logo?<PdfImage src={logo} style={{width:145,height:54,objectFit:'contain'}}/>:<><Text style={styles.brand}>SOLARIS</Text><Text style={styles.subtitle}>ENERGY SOLUTIONS</Text></>}<Text style={styles.muted}>Iluminando el mañana</Text></View><View><Text style={styles.bold}>{record.folio}</Text><Text style={styles.muted}>{d.date.split('-').reverse().join('/')}</Text><Text style={styles.muted}>Reporte de servicio</Text></View></View>
 <Text style={styles.title}>{d.type}</Text>
 <View style={styles.row}><View style={styles.field}><Text style={styles.label}>CLIENTE</Text><Text>{record.customer_name}</Text></View><View style={styles.field}><Text style={styles.label}>TÉCNICO RESPONSABLE</Text><Text>{d.technician}</Text></View></View>
 <View style={styles.row}><View style={styles.field}><Text style={styles.label}>UBICACIÓN</Text><Text>{d.location}</Text></View><View style={styles.field}><Text style={styles.label}>SISTEMA</Text><Text>{record.system_code}</Text></View></View>
 {details.length>0&&<><Heading>Información del sistema</Heading>{details.map(([label,value])=><View key={label} style={styles.row} wrap={false}><Text style={{width:'34%',color:'#5D6C7B'}}>{label}</Text><Text style={{width:'62%'}}>{value}</Text></View>)}</>}
 <Heading>Servicio realizado</Heading><Lines text={d.activities}/>
 {d.findings.length>0&&<><Heading ahead={160}>Hallazgos</Heading>{d.findings.map(f=><View key={f.id} style={styles.box} wrap={false}><Text style={styles.bold} minPresenceAhead={35}>{f.title}</Text><Text style={{fontSize:8,color:gold,marginBottom:5}}>{f.state}</Text><Text orphans={2} widows={2}>{f.description}</Text>{d.photos.some(p=>p.findingIds.includes(f.id))&&<Text style={styles.muted}>Evidencia: {d.photos.map((p,i)=>p.findingIds.includes(f.id)?`Foto ${i+1}`:null).filter(Boolean).join(', ')}.</Text>}</View>)}</>}
 {(d.corrections.trim()||d.result.trim())&&<><Heading>Trabajos realizados y resultado</Heading><Lines text={d.corrections}/><Lines text={d.result}/></>}
 {d.photos.length>0&&<><Heading ahead={250}>Evidencia fotográfica</Heading>{photoRows.map((row,i)=><View key={i} style={{flexDirection:'row',justifyContent:'space-between'}} wrap={false}>{row.map(p=><View key={p.id} style={styles.photo}><PdfImage src={images[p.id]} style={styles.photoImage}/><Text style={styles.caption}><Text style={styles.bold}>Foto {d.photos.findIndex(item=>item.id===p.id)+1} · {p.category}. </Text>{p.description}</Text></View>)}</View>)}</>}
 {d.measurements.length>0&&<><Heading>Mediciones registradas</Heading><View style={styles.tableHead} wrap={false}>{['Parámetro','Valor','Unidad','Observación'].map((name,i)=><Text key={name} style={{width:[ '28%','17%','15%','40%'][i]}}>{name}</Text>)}</View>{d.measurements.map(m=><View key={m.id} style={styles.tableRow} wrap={false}>{[m.parameter,m.value,m.unit,m.observation].map((value,i)=><Text key={i} style={{width:['28%','17%','15%','40%'][i]}}>{value||'—'}</Text>)}</View>)}</>}
 {d.recommendations.length>0&&<><Heading ahead={160}>Recomendaciones</Heading>{d.recommendations.map(r=><View key={r.id} style={styles.box} wrap={false}><Text style={styles.bold} minPresenceAhead={30}>{r.title}</Text><Text style={{fontSize:8,color:gold,marginBottom:5}}>{r.priority}</Text><Text orphans={2} widows={2}>{r.description}</Text></View>)}</>}
 <Heading>Estado general</Heading><Text style={styles.bold}>{d.generalState}</Text>{d.finalComments.trim()&&<Lines text={d.finalComments}/>}{d.nextDate&&<Text>Próximo mantenimiento recomendado: {d.nextDate.split('-').reverse().join('/')}.</Text>}
 <Heading>Conclusión</Heading><Lines text={d.conclusion}/>
 <View style={styles.contact} wrap={false}><View style={{width:'76%'}}><Text style={styles.bold}>SOLARIS Energy Solutions</Text><Text>Instagram: @es_solaris.mx</Text><Text>solarisenergysolutions.mx@gmail.com</Text><Text style={[styles.muted,{marginTop:8}]}>Pasaporte Solar · La historia de tu sistema, a un escaneo.</Text><Link src={passportUrl} style={{fontSize:8,color:gold}}>Abrir expediente de {record.system_code}</Link></View><PdfImage src={qr} style={styles.qr}/></View>
 
 </Page></Document>;
}
export async function buildServicePdf(record:ServiceRecord,images:Record<string,string>,origin:string,logo?:string) {
 const passportUrl=`${origin.replace(/\/$/,'')}/s/${record.public_token}`;
 const qr=await toDataURL(passportUrl,{width:240,margin:2,errorCorrectionLevel:'M'});
 return pdf(<ServiceReportDocument record={record} images={images} qr={qr} passportUrl={passportUrl} logo={logo}/>).toBlob();
}
