import { FileCheck2, ArrowDown } from "lucide-react";
import { MarketingSite, marketingMetadata, Action, ContactBand, FAQ } from "@/components/marketing-site";
const services = [
  ["Interconexión fotovoltaica", "Te orientamos sobre el trámite de interconexión de tu sistema y la documentación correspondiente."],
  ["Nuevos servicios", "Revisamos tu caso para definir los pasos y requisitos aplicables a una nueva solicitud de servicio."],
  ["Medidor bidireccional", "Te acompañamos en la gestión relacionada con el cambio de medidor para tu instalación fotovoltaica."],
  ["Diagramas y documentación", "Definimos la documentación técnica necesaria para tu sistema o trámite, según el alcance de tu solicitud."],
];
export const metadata = marketingMetadata("Gestoría CFE e interconexión en Yucatán | SOLARIS", "Orientación para interconexión fotovoltaica, nuevos servicios, medidor bidireccional y documentación técnica. Consulta tu caso con SOLARIS.", "/gestoria");
export default function ProceduresPage() {
  return <MarketingSite topic="Gestoría">
    <section id="hero" className="landing-hero"><div className="landing-wrap landing-hero-grid"><div><p className="landing-eyebrow">Gestoría y trámites · Yucatán</p><h1>Tu trámite,<br /><span>con un camino claro.</span></h1><p className="landing-intro">Interconexión, nuevos servicios o medidor bidireccional. Cuéntanos en qué etapa estás y te orientamos sobre el siguiente paso.</p><div className="landing-actions"><Action href="/contacto?servicio=Gestor%C3%ADa">Consultar mi trámite</Action><a href="#tramites" className="landing-secondary">Ver servicios ↓</a></div></div><div className="procedure-art"><FileCheck2 size={40} aria-hidden="true" /><p className="landing-eyebrow">Acompañamiento SOLARIS</p><h2>Menos dudas.<br /><span>Más claridad.</span></h2><ol><li><span>01</span> Entendemos tu caso</li><li><span>02</span> Revisamos lo necesario</li><li><span>03</span> Definimos cómo avanzar</li></ol><ArrowDown size={22} aria-hidden="true" /></div></div></section>
    <section id="tramites" className="landing-wrap landing-section"><div className="section-heading"><div><p className="landing-eyebrow">Nuestros servicios</p><h2>Orientación según tu caso.</h2></div><p>No necesitas conocer el nombre exacto del trámite. Podemos ayudarte a identificarlo.</p></div><div className="procedure-list">{services.map(([title, text], i) => <article key={title}><span className="step-index">0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="landing-fine">El alcance se define al revisar tu caso. Los requisitos, tiempos y resoluciones corresponden a la autoridad o entidad responsable del trámite.</p></section>
    <section className="soft-section"><div className="landing-wrap landing-section editorial-grid"><div><p className="landing-eyebrow">Para empezar</p><h2>Con una conversación<br />es suficiente.</h2><p className="landing-lead">Cuéntanos tu ubicación y qué quieres resolver. Si ya iniciaste un trámite, indícanos en qué etapa está.</p></div><FAQ questions={[["¿Pueden ayudarme si ya inicié el trámite?", "Cuéntanos en qué etapa estás. Revisamos tu situación para confirmar cómo podemos apoyarte y definir el alcance."], ["¿Qué documentos debo enviar?", "Primero identificamos tu caso. Después te indicamos qué documentación se necesita; no hace falta tenerla toda para pedir orientación."], ["¿Cuánto cuesta la gestoría?", "La cotización depende del trámite, su etapa y el alcance del acompañamiento. Te presentamos la propuesta antes de comenzar."]]} /></div></section>
    <ContactBand title="Dinos qué necesitas resolver." text="Te ayudamos a identificar el trámite y a definir los siguientes pasos." topic="Gestoría" />
  </MarketingSite>;
}
